##############################################################
##############################################################
# This is an example configuration provided by Wraith.
# Feel free to amend for your own requirements.
# ---
# This particular config is intended to demonstrate how
# to use Wraith in 'history' mode, which is best suited to
# making sure your site's appearance remains consistent over
# time.
#
# `wraith history history.yaml` # generate base screenshots
# `wraith latest history.yaml`  # take new shots and compare
#
##############################################################
##############################################################

# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
browser: "phantomjs"

# AKG: Rendering apps:
# specialist-frontend
# whitehall-frontend
# government-frontend
# frontend
# calendars
# finder-frontend
# manuals-frontend
# collections
# service-manual-frontend
# smartanswers
# (required) The domain to take screenshots of.
domains:
  english: "https://www.gov.uk"

# (required) The paths to capture. This particular config is using casperjs, so we can take screenshots of selectors rather than the entire page.
paths:
  test0: /student-finance-calculator?akg
  test1: /student-finance-calculator?akg
  test2: /student-finance-calculator?akg
  test3: /student-finance-calculator?akg
  test4: /student-finance-calculator?akg
  test5: /student-finance-calculator?akg
  test6: /student-finance-calculator?akg
  test7: /student-finance-calculator?akg
  test8: /student-finance-calculator?akg
  test9: /student-finance-calculator?akg
  test10: /student-finance-calculator?akg
  test11: /student-finance-calculator?akg
  test12: /student-finance-calculator?akg
  test13: /student-finance-calculator?akg
  test14: /student-finance-calculator?akg
  test15: /student-finance-calculator?akg
  test16: /student-finance-calculator?akg
  test17: /student-finance-calculator?akg
  test18: /student-finance-calculator?akg
  test19: /student-finance-calculator?akg
  test20: /student-finance-calculator?akg
  test21: /student-finance-calculator?akg
  test22: /student-finance-calculator?akg
  test23: /student-finance-calculator?akg
  test24: /student-finance-calculator?akg
  test25: /student-finance-calculator?akg
  test26: /student-finance-calculator?akg
  test27: /student-finance-calculator?akg
  test28: /student-finance-calculator?akg
  test29: /student-finance-calculator?akg
  test30: /student-finance-calculator?akg
  test31: /student-finance-calculator?akg
  test32: /student-finance-calculator?akg
  test33: /student-finance-calculator?akg
  test34: /student-finance-calculator?akg
  test35: /student-finance-calculator?akg
  test36: /student-finance-calculator?akg
  test37: /student-finance-calculator?akg
  test38: /student-finance-calculator?akg
  test39: /student-finance-calculator?akg
  test40: /student-finance-calculator?akg
  test41: /student-finance-calculator?akg
  test42: /student-finance-calculator?akg
  test43: /student-finance-calculator?akg
  test44: /student-finance-calculator?akg
  test45: /student-finance-calculator?akg
  test46: /student-finance-calculator?akg
  test47: /student-finance-calculator?akg
  test48: /student-finance-calculator?akg
  test49: /student-finance-calculator?akg
  test50: /student-finance-calculator?akg
  test51: /student-finance-calculator?akg
  test52: /student-finance-calculator?akg
  test53: /student-finance-calculator?akg
  test54: /student-finance-calculator?akg
  test55: /student-finance-calculator?akg
  test56: /student-finance-calculator?akg
  test57: /student-finance-calculator?akg
  test58: /student-finance-calculator?akg
  test59: /student-finance-calculator?akg
  test60: /student-finance-calculator?akg
  test61: /student-finance-calculator?akg
  test62: /student-finance-calculator?akg
  test63: /student-finance-calculator?akg
  test64: /student-finance-calculator?akg
  test65: /student-finance-calculator?akg
  test66: /student-finance-calculator?akg
  test67: /student-finance-calculator?akg
  test68: /student-finance-calculator?akg
  test69: /student-finance-calculator?akg
  test70: /student-finance-calculator?akg
  test71: /student-finance-calculator?akg
  test72: /student-finance-calculator?akg
  test73: /student-finance-calculator?akg
  test74: /student-finance-calculator?akg
  test75: /student-finance-calculator?akg
  test76: /student-finance-calculator?akg
  test77: /student-finance-calculator?akg
  test78: /student-finance-calculator?akg
  test79: /student-finance-calculator?akg
  test80: /student-finance-calculator?akg
  test81: /student-finance-calculator?akg
  test82: /student-finance-calculator?akg
  test83: /student-finance-calculator?akg
  test84: /student-finance-calculator?akg
  test85: /student-finance-calculator?akg
  test86: /student-finance-calculator?akg
  test87: /student-finance-calculator?akg
  test88: /student-finance-calculator?akg
  test89: /student-finance-calculator?akg
  test90: /student-finance-calculator?akg
  test91: /student-finance-calculator?akg
  test92: /student-finance-calculator?akg
  test93: /student-finance-calculator?akg
  test94: /student-finance-calculator?akg
  test95: /student-finance-calculator?akg
  test96: /student-finance-calculator?akg
  test97: /student-finance-calculator?akg
  test98: /student-finance-calculator?akg
  test99: /student-finance-calculator?akg



# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
before_capture: 'javascript/cookies_and_headers--phantom.js'

# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
screen_widths:
  # - 320
  # - 768
  - 1280

# (optional) Resize to each screen width (efficient), or reload at each screen width (costly). Default: 'reload'
resize_or_reload: 'resize'

# (required for history mode, otherwise optional) The directory that your base screenshots will be stored in.
history_dir: 'shots_base'

# (required) The directory that your latest screenshots will be stored in
directory: 'shots'

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '20%'

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
mode: diffs_first

# (optional) Choose to run Wraith in verbose mode, for easier debugging. Default: false
verbose: true

# (optional) Color to highlight the image diff. Default: 'blue'
highlight_color: red

# (optional) Parameters to pass to Phantom/Casper command line. Default: '--ignore-ssl-errors=true --ssl-protocol=tlsv1'
phantomjs_options: ''
